//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateFor_Vosmerka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Make = new HashSet<Make>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public int MaterialTypeID { get; set; }
        public Nullable<int> QuantityInPac { get; set; }
        public int QuantityTypeID { get; set; }
        public Nullable<int> QuantityInHub { get; set; }
        public Nullable<int> MinQuantity { get; set; }
        public Nullable<double> Cost { get; set; }
    
        public virtual ICollection<Make> Make { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual QuantityType QuantityType { get; set; }
    }
}
