//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateFor_Vosmerka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Make = new HashSet<Make>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Article { get; set; }
        public Nullable<int> MinCost { get; set; }
        public string Image { get; set; }
        public int ProductTypeID { get; set; }
        public Nullable<int> HumanResourses { get; set; }
        public int ProductPlaseId { get; set; }
    
        public virtual ICollection<Make> Make { get; set; }
        public virtual ProductPlace ProductPlace { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
