//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateFor_Vosmerka
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public ProductType()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int ProductTypeID { get; set; }
        public string ProductTypeName { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
